# Generated by Django 4.0.4 on 2022-05-01 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=150)),
                ('tasktype', models.BooleanField(default=False)),
                ('taskdate', models.DateField(default=datetime.date)),
                ('taskduration', models.BigIntegerField(default=1)),
            ],
        ),
    ]
