# Generated by Django 4.0.4 on 2022-05-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_taskdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='taskdate',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='taskduration',
        ),
        migrations.AddField(
            model_name='appointment',
            name='EndTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='StartTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='subject',
            field=models.CharField(default='Current', max_length=150),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tasktype',
            field=models.CharField(default='soft', max_length=150),
        ),
    ]
