# Generated by Django 4.0.4 on 2022-05-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_appointment_task_remove_appointment_taskdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='EndTime',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='StartTime',
        ),
        migrations.AddField(
            model_name='appointment',
            name='taskduration',
            field=models.BigIntegerField(default=1),
        ),
    ]
