# Generated by Django 4.0.4 on 2022-05-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_remove_appointment_endtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='subject',
            new_name='endDate',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='taskduration',
        ),
        migrations.AddField(
            model_name='appointment',
            name='startDate',
            field=models.CharField(default='Current', max_length=150),
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='Current', max_length=150),
        ),
    ]
